name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed lib

      - name: Test
        run: flutter test

      - name: build
        if: github.ref_name == 'cicd'
        run: flutter build apk --debug

      - name: Upload artifact
        if: github.ref_name == 'cicd'
        uses: actions/upload-artifact@v4
        with:
          path: build/app/outputs/apk/debug/app-debug.apk
